import type { Generated, Insertable, Selectable, Updateable } from 'kysely';

export interface ReservationTable {
  // Columns that are generated by the database should be marked
  // using the `Generated` type. This way they are automatically
  // made optional in inserts and updates.
  id: Generated<number>;
  user_id: number;
  day: Date;
  from_hour: number;
  to_hour: number;
}

export type Reservation = Selectable<ReservationTable>;
export type NewReservation = Insertable<ReservationTable>;
export type ReservationUpdate = Updateable<ReservationTable>;
